# ──────────────────────────────────
# Ref: https://mark.stosberg.com/fuzzel-1-13-adds-new-features-for-menu-building-and-usability/
# Ref: https://mark.stosberg.com/fuzzel-a-great-dmenu-and-rofi-altenrative-for-wayland/
# Ref: https://codeberg.org/dnkl/fuzzel/pulls/645?ref=mark.stosberg.com
# Ref: https://github.com/catppuccin/fuzzel
# ──────────────────────────────────

#prompt="❯   "

# ──────────────────────────────────
# Сatppuccin Sky theme with background alpha 95% (f2) and Nord Frost (Dark) border color (#5e81acff)
# ──────────────────────────────────
[colors]
background=1e1e2ef2
text=cdd6f4ff
message=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=89dcebff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=89dcebff
counter=7f849cff
border=5e81acff

#[dmenu]
#exit-immediately-if-empty=yes
