# ══════════════════════════════════════════════════
# Ref: https://docs.gtk.org/gtk3/class.Settings.html
# Ref: https://docs.gtk.org/gtk4/class.Settings.html
# ══════════════════════════════════════════════════
[org/gnome/desktop/interface]
# [default | prefer-dark | prefer-light]
color-scheme='prefer-dark'
document-font-name='Adwaita Sans 12'
# [true | false]
enable-animations=false
# [none | grayscale | rgba]
font-antialiasing='grayscale'
# [none | slight | medium | full]
font-hinting='slight'
font-name='Adwaita Sans 11'
# [manual | automatic]
# manual - соблюдение низкоуровневых настроек
# automatic - предоставление инструментарию принимать собственные решения
font-rendering='automatic'
# Порядок субпиксельных элементов на ЖК-экране; только если установлен тип сглаживания «rgba»
# [rgba | rgb | bgr | vrgb | vbgr]
font-rgba-order='rgba'
[true | false]
gtk-enable-primary-paste=false
# [Adwaita | adw-gtk3 | adw-gtk3-dark]
gtk-theme='Adwaita'
# [Adwaita | MoreWaita | Numix | Numix-Light | Numix-Circle | Numix-Circle-Light | ...  ]
# [Numix-Adwaita | Numix-Adwaita-Light] - моя кастомная тема
icon-theme='Adwaita'
monospace-font-name='Adwaita Mono 11'
# [true | false]
overlay-scrolling=true
# Целое число (Int 32), используемое как коэффициент масштабирования окон для экранов с высоким разрешением. «0» — выбрать автоматически, в зависимости от монитора.
# То же самое что переменная - GDK_SCALE
# [0 | 1 | 2 | 3 ...]
scaling-factor=uint32 0
# Коэффициент масштабирования текста (при изменении коэффициента размер шрифта не изменяется).
# То же самое что переменная - GDK_DPI_SCALE
# [Минимально = 0.5 | По умолчанию = 1.0 | Максимально = 3.0]
text-scaling-factor=1.0
# [small | large]
toolbar-icons-size='small'

[org/gnome/desktop/wm/preferences]
button-layout='appmenu:minimize,maximize,close'
# Некоторые приложения игнорируют спецификации,
# что приводит к использованию неправильных свойств оконным менеджером.
# Данный параметр устанавливает оконный менеджер в строгий режим,
# который предоставляет более единообразный интерфейс при условии,
# что не нужно запускать некорректные приложения.
# [true | false]
disable-workarounds=true
