# systemctl --user daemon-reload && systemctl --user stop wob.service wob.socket && rm -f "$XDG_RUNTIME_DIR/wob.sock" && systemctl --user reset-failed && systemctl --user start wob.socket
anchor = bottom right
