* soft stack 16384
* hard stack 16384

* soft nofile 1048576
* hard nofile 1048576

@audio soft rtprio 99
@audio hard rtprio 99
@audio soft memlock unlimited
@audio hard memlock unlimited
@audio soft nice -20
@audio hard nice -20
