--password-store=basic

--ozone-platform=wayland
--ozone-platform-hint=wayland
--gtk-version=4

--use-cmd-decoder=passthrough
--disable-gpu-sandbox

--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiIgnoreDriverChecks,UseOutOfProcessVideoDecoding,HeavyAdPrivacyMitigations,V8VmFuture,ParallelDownloading

--ignore-gpu-blocklist
--disable-gpu-driver-bug-workarounds
--enable-gpu-rasterization
--enable-native-gpu-memory-buffers
--enable-zero-copy

--enable-unsafe-webgpu
--disable-webgl
--enable-experimental-web-platform-features
--enable-experimental-webassembly-features

--enable-quic
--javascript-harmony
--v8-cache-options=code

--disable-sync
--no-pings

--disable-smooth-scrolling
