--no-default-browser-check
--password-store=basic
--disk-cache-dir=/tmp/chromium-cache

--ozone-platform=wayland
--ozone-platform-hint=wayland
--gtk-version=4

--use-cmd-decoder=passthrough
--disable-gpu-sandbox

--enable-features=AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,VaapiIgnoreDriverChecks,UseOutOfProcessVideoDecoding,HeavyAdPrivacyMitigations,V8VmFuture,ParallelDownloading,TouchpadOverscrollHistoryNavigation,WebRtcPipeWireCamera,WebContentsForceDark:inversion_method/cielab_based/image_behavior/none/foreground_lightness_threshold/150/background_lightness_threshold/205

--ignore-gpu-blocklist
--disable-gpu-driver-bug-workarounds

--enable-gpu-rasterization
--enable-native-gpu-memory-buffers
--enable-zero-copy

--enable-unsafe-webgpu
--enable-webgpu-developer-features
--disable-webgl
--enable-experimental-web-platform-features
--enable-experimental-webassembly-features

--enable-quic
--javascript-harmony
--v8-cache-options=code

--force-dark-mode
--disable-smooth-scrolling

--no-pings
--disable-sync
--disable-crash-reporter
