# https://docs.gtk.org/gtk3/class.Settings.html
[Settings]
gtk-application-prefer-dark-theme=true
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24
gtk-decoration-layout=appmenu:minimize,maximize,close
gtk-enable-animations=false
gtk-enable-primary-paste=true
gtk-font-name=Adwaita Sans 11
gtk-icon-theme-name=Adwaita
gtk-overlay-scrolling=true
