#===============================#
# Kitty Default theme:
#===============================#

# Default colors
[colors.primary]
background = "#000000"
foreground = "#FEFEFE"

# Normal colors
[colors.normal]
black      = "#000000"
red        = "#C30302"
green      = "#18CA00"
yellow     = "#CDCA00"
blue       = "#0C72CB"
magenta    = "#CA1DD0"
cyan       = "#0CCCCC"
white      = "#DDDDDD"

# Bright colors
[colors.bright]
black      = "#747474"
red        = "#F21F1E"
green      = "#22FD00"
yellow     = "#FEFD00"
blue       = "#198FFE"
magenta    = "#FD27FE"
cyan       = "#13FEFE"
white      = "#FEFEFE"
