# =============================================
# Ref: https://wiki.archlinux.org/title/Power_management#Intel_wireless_cards_(iwlwifi)
# =============================================
# Полностью отключаем управление питанием драйвера
options iwlwifi power_save=0
