# ══════════════════════════════════════════════════
# Ref: https://thesofproject.github.io/latest/getting_started/intel_debug/introduction.html
# ══════════════════════════════════════════════════
blacklist snd_soc_avs
blacklist snd_hda_intel
options snd-intel-dspcfg dsp_driver=3
#
# Blacklist all
# blacklist snd_soc_avs
# blacklist snd_hda_intel
# blacklist snd_sof_pci_intel_tgl
